version: "3.9"
services:
  psql:
    image: postgres:16.0-alpine
    container_name: psql
    networks:
      - local_net
    ports:
      - "54321:5432"
    volumes:
      - "/tmp/users-data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test-user -d users"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  usersrv:
    build: .
    container_name: usersrv
    image: usersrvimg
    ports:
      - "8081:8082"
    links:
      - "psql:database"
    networks:
      - local_net

networks:
  local_net:
    name: local_net
