version: "3.9"
services:
  psql:
    image: postgres:16.0-alpine
    ports:
      - "54321:5432"
    volumes:
      - "/tmp/postgres-data:/var/lib/postresql/data"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
