my:
  db:
    schemaname: users_scheme

spring:
  jpa:
    #database: postgresql
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${my.db.schemaname}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/users
    username: test-user
    password: test-password
  liquibase:
    default-schema: ${my.db.schemaname}

logging.level:
  org.hibernate: INFO
  org.hibernate.SQL: DEBUG
  org.hibernate.cache: DEBUG
  org.hibernate.stat: DEBUG
logging:
  level:
    root: info
