my:
  db:
    schemaname: users_scheme

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${my.db.schemaname}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://psql:5432/users
    username: test-user
    password: test-password
  liquibase:
    default-schema: ${my.db.schemaname}
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8082

logging.level:
  org.hibernate: INFO
  org.hibernate.SQL: DEBUG
  org.hibernate.cache: DEBUG
  org.hibernate.stat: DEBUG
  root: info
